# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rW4cu28c-c_n77TXHuWw9dNaa5NOvdSB
"""

import math
def calculate_volume_of_sphere(radius):
  volume = (4/3) * math.pi * radius**3
  print(volume)

calculate_volume_of_sphere(30)
calculate_volume_of_sphere(40)